### ISSUE TITLE
List of TODO items

### ISSUE THREAD

**Issue by hsunpei** [iCHEF/transcharts#25]
## Release
- [ ] Release the npm package
- [ ] Auto release by github action

## Documentations
- [x] Update the sample data to make the examples more intelligible

## Line Chart & Bar Chart
- [x] Tooltip: display all values of the same column like [c3](https://c3js.org/samples/chart_bar_stacked.html)
![Screen Shot 2019-03-15 at 2 29 04 PM](https://user-images.githubusercontent.com/1139698/54412733-d8a0df00-472e-11e9-8f93-e15536556a4b.png)

- [ ] Display a horizontal line at zero if there are negative y values like [c3](https://c3js.org/samples/chart_bar_stacked.html)
![Screen Shot 2019-03-15 at 2 31 23 PM](https://user-images.githubusercontent.com/1139698/54412910-2d445a00-472f-11e9-955f-d95670ddfbc9.png)

- [x] Display labels [along the axes](https://vx-demo.now.sh/axis)
- [ ] Format the datetime and integer values
- [ ] Integrate animations to the charts

## Bar Chart
- [ ] Add histograms
- [x] Support [horizontal bar charts](https://github.com/iCHEF/transcharts/issues/13)
- [ ] Support [bar group](https://github.com/iCHEF/transcharts/issues/13)
